# Generated by Django 4.2.10 on 2024-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_menu_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
