# Generated by Django 4.2.10 on 2024-03-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Meals", new_name="Menu",),
    ]
