# Generated by Django 4.2.10 on 2024-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_menu_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu", name="people", field=models.IntegerField(default=0),
        ),
    ]
