# Generated by Django 4.2.10 on 2024-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0004_menu_people"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="category",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Menu",),
    ]
